### PR TITLE
Non-localhost brokers

### PR DESCRIPTION
**Pull request by nwf**

### CODE REVIEW

**Comment by timparenti** [comment]
It looks like @michaelfelixmurphy got the typo independently in https://github.com/cmukgb/ctfws-timer-web/commit/56df7a82cd58871cd88eb78195ac68a6c1721eb4.

**Comment by timparenti** [comment]
That said, the non-localhost brokers stuff is probably reasonable, if you want to rebase, @nwf?

**Comment by michaelfelixmurphy** [comment]
There were some things I wanted to change about the non-localhost stuff and I haven't made it a priority. I sort of want to get to this after a bunch of the other issues, and it sounds like @nwf at least has what he needs locally for now? I have no need for non-localhost broker support myself at the moment.

**Comment by nwf** [comment]
Not urgent by any means, though with all the changes we're making, I wonder to what extent it makes sense to continue to have the server know anything about the broker at all.  Can we offload it all to the client and the magic of websockets?

**Comment by michaelfelixmurphy** [comment]
You mean have the web client publish to the broker directly rather than AJAX POSTing and running a script? A very reasonable design (and of course the more normal option). Two issues:
- That's a lot of refactoring for no visible reward. I have a bunch of features I want to get to first.
- That would require the web client to know some MQTT password in plaintext in the source. Currently Django handles all the authentication, CRSF checking, etc, and then the server uses the password it has stored relatively securely. (Of course all of this is a little defeated by the fact they we're not using HTTPS.)

**Comment by nwf** [comment]
Yeah, that's what I meant.  I understand there's no immediate gain and no real reason to prioritize it.

I think, tho', that the password would only have to be in plaintext on the client; we could ask the judges to log in to the broker directly, and have a server-side script to rotate the broker-side passwords (and presumably kick off the old clients).  We'd have to see about the details. :)

**Comment by nwf** [comment]
@timparenti This appears to have been closed automatically and probably shouldn't be.

**Comment by timparenti** [comment]
When renaming the default branch of this repo from `master` to `main`, all PRs opened against the former were retargeted against the latter.  But it seems in this case that the source repo for this PR has been deleted, so Github took that as a sign to close it.

@nwf I'm not able to re-open the PR because there's no repo tied to it anymore, but it looks like [a rebase had been requested anyway](https://github.com/cmukgb/ctfws-timer-web/pull/5#issuecomment-469089739), so please do resubmit.

**Pull request closed without merging**
